demo:
  isopen: true
  say-what: hello
  to-who: shf


server:
  port: 8989
spring:
  datasource:
    master:
      password: Aa111111$
      url: jdbc:mysql://localhost:3306/aegis?useUnicode=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: lusty
      type: com.zaxxer.hikari.HikariDataSource

    cluster:
    - key: app
      password: Aa111111$
      url: jdbc:mysql://localhost:3306/app?useUnicode=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: lusty
      type: com.zaxxer.hikari.HikariDataSource



mybatis:
  type-aliases-package: com.lusty.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug